### ISSUE TITLE
AttributeError: module 'k_diffusion' has no attribute 'external'

### ISSUE THREAD

**Issue by laidingq** [smthemex/ComfyUI_Diffree#4]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\__init__.py", line 2, in <module>
    from .Diffree_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\Diffree_node.py", line 144, in <module>
    class CompVisDenoiser(K.external.CompVisDenoiser):
                          ^^^^^^^^^^
AttributeError: module 'k_diffusion' has no attribute 'external'

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_Diffree module for custom nodes: module 'k_diffusion' has no attribute 'external'

**Comment by smthemex** [comment]
i will fix it ，wait a moment

**Comment by smthemex** [comment]
I have added the k_diffusion library for easy use in portable ComfyUI. Please check the new version and readme

**Comment by laidingq** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\__init__.py", line 2, in <module>
    from .Diffree_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\Diffree_node.py", line 10, in <module>
    from . import k_diffusion as K
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\k_diffusion\__init__.py", line 2, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\k_diffusion\config.py", line 6, in <module>
    from jsonmerge import merge
ModuleNotFoundError: No module named 'jsonmerge'

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_Diffree module for custom nodes: No module named 'jsonmerge'
更新后出现这个问题，我环境里有这个

**Comment by laidingq** [comment]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\__init__.py", line 2, in <module>
    from .Diffree_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\Diffree_node.py", line 10, in <module>
    from . import k_diffusion as K
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\k_diffusion\__init__.py", line 2, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "D:\ComfyUI\custom_nodes\ComfyUI_Diffree\k_diffusion\evaluation.py", line 6, in <module>
    import clip
  File "D:\ComfyUI\miniconda\Lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "D:\ComfyUI\miniconda\Lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (D:\ComfyUI\miniconda\Lib\site-packages\pkg_resources\__init__.py)

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_Diffree module for custom nodes: cannot import name 'packaging' from 'pkg_resources' (D:\ComfyUI\miniconda\Lib\site-packages\pkg_resources\__init__.py)

**Comment by smthemex** [comment]
装下clip-anytorch 库，你可以对照 K diffusion的库来装缺失的，看你最后的报错，可能是clip版本不支持

**Comment by laidingq** [comment]
clip-anytorch==2.6.0  还是同样的错误

**Comment by laidingq** [comment]
已经加载运行成功  需要setuptools==69.5.1
